server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root

  config:
    import: "optional:configserver:"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Microservice Plazoleta de comidas"
appVersion: "1.0.0"
